### ISSUE TITLE
.NET Core/Standard version is not strong name signed

### ISSUE THREAD

**Issue by tomrus88** [moonsharp-devs/moonsharp#239]
As title says, MoonSharp nuget package includes MoonSharp.Interpreter.dll that is not strong name signed for .NET Core and .NET Standard targets, which is causing issues: https://github.com/dotnet/project-system/issues/4424

**Comment by berbun** [comment]
@tomrus88 
There is no .NET Core in the NuGet package; MoonSharp isn't targetting .NET Core (from what I can tell).
Looking at the end of the issue page on the link you posted, it seems you have figured that.

You'd just take MoonSharp sources and create .NET Standard project, and woila, done in less than 5 minutes. It should be that easy (given that you're targetting .NET Standard v2.0, since v2.1 does not support .NET Framework).

**Comment by LimpingNinja** [comment]
Thanks for updating this, sorry for the delay. If it helps, I'm using it in production on .NET Core 2.2
