### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qxa792** [moonsharp-devs/moonsharp#262]
![image](https://user-images.githubusercontent.com/53459088/66727202-253ccc00-ee70-11e9-8c01-9d110830fce3.png)
![image](https://user-images.githubusercontent.com/53459088/66727219-3ede1380-ee70-11e9-90e3-b9b60e09c0c9.png)
![image](https://user-images.githubusercontent.com/53459088/66727222-43a2c780-ee70-11e9-8ef1-6211a6e25b2a.png)

**Comment by admalledd** [comment]
You need to register the types otherwise Moonsharp won't know to auto-convert for you.

See for example: https://github.com/moonsharp-devs/moonsharp/blob/master/src/Tutorial/Tutorials/Chapters/Chapter6.cs#L169

and http://www.moonsharp.org/objects.html and http://www.moonsharp.org/mapping.html have some notes about registering types.

You can also set your own Type Registration Policy (eg allow all types of namespace, all types in certain assemblies...) see https://github.com/moonsharp-devs/moonsharp/blob/master/src/MoonSharp.Interpreter/Interop/RegistrationPolicies/AutomaticRegistrationPolicy.cs for the automatic version. 

`UserData.RegistrationPolicy = InteropRegistrationPolicy.Automatic;` (NOT recommended if code is untrusted!)

**Comment by qxa792** [comment]
thanks
